### ISSUE TITLE
Making more reproducible archive files

### ISSUE THREAD

**Issue by detrout** [pycompression/xopen#94] opened 2022-03-03 23:38 UTC
Hi,

I was trying to make it easier for one of my projects to generate gziped files with a constant md5sum. By default gzip includes the filename and original file mtime, which unfortunately causes the cryptographic hashes to be different every time you create the file.

It'd be nice if xopen had a way to enable the --no-name option for gzip/pigz

**Comment by rhpvorderman** [comment] 2022-03-04 08:38
This is essentially a duplicate of #26. We have not implemented such a thing yet. bzip2 and xz files do not store any timestamp. 

There are two ways to this:
1. Add an extra parameter to xopen (mtime), but that would only work with gzip and therefore clutter the API.
2. Always produce reproducible gzip.

Given that uncompressed files do not store a timestamp either, I think there are no users who use xopen AND rely on a correctly set mtime field in gzip files produced by xopen. So I prefer option 2. Reproducibility is always a nice bonus for scientific applications that use xopen. 

What do you think @marcelm?

**Comment by marcelm** [comment] 2022-03-04 11:46
I’m also in favor of making gzip files always reproducible.

This would need to be done for all the ways we support for writing gzip files. Both `gzip` and `pigz` have a `--no-name` option, but `python -m isal.igzip` doesn’t at the moment, is that something you could add easily?

**Comment by rhpvorderman** [comment] 2022-03-04 12:54
Sure. It seems like `gzip`, `pigz` and `igzip` all use the same flag for this. I will add that for python-isal `1.0.0`. Hopefully ISA-L releases soon now. They had a release planned  "in the new year" (2022), but I will ask them again.

**Comment by detrout** [comment] 2022-03-04 17:05
That all sounds promising.

Thank you

**Comment by marcelm** [comment] 2022-03-08 14:29
I’ve started work on this in #97.

**Comment by rhpvorderman** [comment] 2022-08-10 11:03
This issue is now solved on the development branch. @detrout you can make use of it by installing `pip install git+https://github.com/pycompression/xopen` to install the latest development version, or wait until the next release.

**Comment by marcelm** [comment] 2022-08-10 12:28
Shall we make a new release?

**Comment by rhpvorderman** [comment] 2022-08-10 13:09
I am all for it. Having cutadapt output reproducible FASTQs is a quite a nice improvement.

**Comment by marcelm** [comment] 2022-08-10 19:45
Version 1.6.0 is now available on PyPI (I guess the conda package will be available at the latest tomorrow).

**Closed by marcelm** 2022-08-10 19:45 UTC
